# Basic
title: Cbottove
subtitle: cbottove's blog
description: Welcome to my blog~
# 头像里面的标题
avatarTitle: hello ctf
# 头像里面的描述
avatarDesc: 
url: "http://cbottave.github.io"

# Comment
#comment:
    #disqus: leopard
    # uyan: 2143225 

# Social
social:
    github: cbottave
    # twitter: 
    mail: cbottave@gmail.com

# Google Analytics

#ga:
    #id:   
    #host: auto  



permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


